services:
  item-service:
    build:
      context: ./item-service
      dockerfile: Dockerfile
    container_name: item-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: local

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: local

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local

  trade-service:
    build:
      context: ./trade-service
      dockerfile: Dockerfile
    container_name: trade-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: local

  pay-service:
    build:
      context: ./pay-service
      dockerfile: Dockerfile
    container_name: pay-service
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: local

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    container_name: search-service
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: local

  hm-gateway:
    build:
      context: ./hm-gateway
      dockerfile: Dockerfile
    container_name: hm-gateway
    ports:
      - "8080:8080"
    depends_on:
      - item-service
      - user-service
      - cart-service
      - trade-service
      - pay-service
      - search-service
    environment:
      SPRING_PROFILES_ACTIVE: local
